currencies_names = {
    "AED":"UAE Dirham",
    "FN":"Afghanistan Afghani",
    "ALL":"Albania Lek",
    "AMD":"Armenia Dram",
    "ANG":"Netherlands Antilles Guilder",
    "AOA":"Angola New Kwanza",
    "ARS":"Argentine Peso",
    "AUD":"Australian Dollar",
    "AWG":"Aruba Guilder",
    "AZN":"Azerbaijan Manat",
    "BAM":"Bosnia & Herzegovina Mark",
    "BBD":"Barbados Dollar",
    "BDT":"Bangladesh Taka",
    "BGN":"Bulgaria Lev",
    "BHD":"Bahrain Dinar",
    "BIF":"Burundi Franc",
    "BMD":"Bermuda Dollar",
    "BND":"Brunei Dollar",
    "BOB":"Bolivia Boliviano",
    "BRL":"Brazil Real",
    "BSD":"Bahamas Dollar",
    "BTN":"Bhutan Ngultrum",
    "BWP":"Botswana Pula",
    "BYR":"Belarus Rouble",
    "BZD":"Belize Dollar",
    "CAD":"Canadian Dollar",
    "CDF":"Democratic Rep of Congo",
    "CHF":"Swiss Franc",
    "CLP":"Chilean Peso",
    "CNY":"China Yuan Renminbi",
    "COP":"Colombia Peso",
    "CRC":"Costa Rica Colon",
    "CUP":"Cuba Peso",
    "CVE":"Cape Verde Escudo",
    "CYP":"Cypriot Pound",
    "CZK":"Czech Republic Koruna",
    "DJF":"Djibouti Franc",
    "DKK":"Danish Krone",
    "DOP":"Dominican Republic Peso",
    "DZD":"Algerian Dinar",
    "EEK":"Estonia Kroon",
    "EGP":"Egyptian Pound",
    "ERN":"Eritrea Nafka",
    "ETB":"Ethiopia Birr",
    "EUR":"Euro",
    "FJD":"Fijian Dollar",
    "FKP":"Falkland Islands Pound",
    "GBP":"UK Sterling",
    "GEL":"Georgia Lari",
    "GHS":"Ghana Cedi",
    "GIP":"Gibraltar Pound",
    "GMD":"Gambia Dalasi",
    "GNF":"Guinea Republic Franc",
    "GTQ":"Guatemala Quetzal",
    "GYD":"Guyana Dollar",
    "HKD":"Hong Kong Dollar",
    "HNL":"Honduras Lempira",
    "HRK":"Croatian Kuna",
    "HTG":"Haiti Gourde",
    "HUF":"Hungary Forint",
    "IDR":"Indonesian Rupiah",
    "ILS":"Israel New Shekel",
    "INR":"Indian Rupee",
    "IQD":"Iraq Dinar",
    "IRR":"Iran Riyal",
    "ISK":"Iceland Krona",
    "JMD":"Jamaica Dollar",
    "JOD":"Jordanian Dinar",
    "JPY":"Japanese Yen",
    "KES":"Kenyan Shilling",
    "KGS":"Kyrgyzstan Som",
    "KHR":"Cambodian Riel",
    "KMF":"Comoros Franc",
    "KPW":"North Korean Won",
    "KRW":"Korean Won",
    "KWD":"Kuwaiti Dinar",
    "KYD":"Cayman Islands Dollar",
    "KZT":"Kazakhstan Tenge",
    "LAK":"Laos Kip",
    "LBP":"Lebanese Pound",
    "LKR":"Sri Lanka Rupee",
    "LSL":"Lesotho Loti",
    "LTL":"Lithuanian Litas",
    "LVL":"Latvian Lats",
    "LYD":"Libya Dinar",
    "MAD":"Moroccan Dihram",
    "MDL":"Moldova Leu",
    "MGA":"Madagascar Ariary",
    "MKD":"Macedonia Denar",
    "MMK":"Myanmar Kyat",
    "MNT":"Mongolia Tugrik",
    "MOP":"Macau Pataca",
    "MRO":"Mauritania Ouguiya",
    "MTL":"Maltese Lira",
    "MUR":"Mauritius Rupee",
    "MVR":"Maldives Rufiyan",
    "MWK":"Malawi Kwacha",
    "MXN":"Mexican New Peso",
    "MYR":"Malaysian Ringgit",
    "MZN":"New Mozambique Metical",
    "NAD":"Namibia Dollar",
    "NGN":"Nigerian Naira",
    "NIO":"Nicaragua Cordoba",
    "NOK":"Norwegian Krone",
    "NPR":"Nepal Rupee",
    "NZD":"New Zealand Dollar",
    "OMR":"Oman Riyal",
    "PAB":"Panama Balboa",
    "PEN":"Peru New Sol",
    "PGK":"Papua New Guinea Kina",
    "PHP":"Philippines Peso",
    "PKR":"Pakistani Rupee",
    "PLN":"Poland Zloty",
    "PYG":"Paraguay Guarani",
    "QAR":"Qatari Riyali",
    "RON":"New Romania Leu",
    "RSD":"Serbia Dinar",
    "RUB":"Russian Ruble",
    "RWF":"Rwanda Franc",
    "SAR":"Saudi Arabian Riyal",
    "SBD":"Solomon Isl Dollar",
    "SCR":"Seychelles Rupee",
    "SDG":"Sudan Pound",
    "SEK":"Swedish Krona",
    "SGD":"Singapore Dollar",
    "SHP":"St Helena Pound",
    "SKK":"Slovack Koruna",
    "SLL":"Sierra Leone Leone",
    "SOS":"Somali Rep Shilling",
    "SRD":"Surinam Dollar",
    "STD":"Sao Tome & Principe Dobra",
    "SVC":"El Salvador Colon",
    "SYP":"Syria Pound",
    "SZL":"Swaziland Lilangeni",
    "THB":"Thai Baht",
    "TJS":"Tajikstan Somoni",
    "TMM":"Turkmenistan Manat",
    "TND":"Tunisian Dinar",
    "TOF":"Thai Baht Offshore",
    "TOP":"Tonga Isl Pa anga",
    "TRY":"New Turkish Lira",
    "TTD":"Trinidad & Tobago Dollar",
    "TWD":"New Taiwan Dollar",
    "TZS":"Tanzanian Shilling",
    "UAH":"Ukraine Hryvnia",
    "UGX":"Uganda Shilling",
    "USD":"United States Dollar",
    "UYU":"Uruguayo Peso",
    "UZS":"Uzbekistan Sum",
    "VEB":"Venezuelan Bolivar",
    "VND":"Vietnam Dong",
    "VUV":"Vanuatu Vatu",
    "WST":"W. Samoa Tala",
    "XAF":"BEAC CFA Franc",
    "XCD":"East Caribbean Dollar",
    "XDR":"Special Drawing Rights",
    "XOF":"BCEAO CFA Franc",
    "XPF":"French Polynesia Franc",
    "YER":"Yemen Riyal",
    "ZAR":"South African Rand",
    "ZMK":"Zambia Kwacha",
    "ZWD":"Zimbabwean Dollar",
}
